### ISSUE TITLE
Removing ad plugins but not setting debugAds to true causes error

### ISSUE THREAD

**Issue by marguinbc** [marguinbc/brightcove-player-debugger#1]
If you want to use the debugger without any ad plugins, removing them from the player or not including them on the page results in an error: 'fw-plugin not found'

Make the debugger smart enough to determine that even if debugAds is set to true, but there is no ad plugin detected, to log a warning instead and continue on.

**Comment by RevinKey** [comment]
This is fixed in latest version.
