### ISSUE TITLE
Throws error and fails in Brightcove Player v6

### ISSUE THREAD

**Issue by silevitas** [marguinbc/brightcove-player-debugger#10]
Logging this for reference. The debugger throws an error with v6:

> Uncaught TypeError: Super expression must either be null or a function, not undefined
>     at r (brightcove-player-debugger.min.js:7)
>     at brightcove-player-debugger.min.js:7
>     at Object.<anonymous> (brightcove-player-debugger.min.js:7)
>     at Object.n.11 (brightcove-player-debugger.min.js:7)
>     at a (brightcove-player-debugger.min.js:7)
>     at brightcove-player-debugger.min.js:7
>     at Object.n.10../componentIDs.js (brightcove-player-debugger.min.js:7)
>     at a (brightcove-player-debugger.min.js:7)
>     at brightcove-player-debugger.min.js:7
>     at Object.n.13../classesList.js (brightcove-player-debugger.min.js:8)

> Uncaught TypeError: myPlayer.playerDebugger is not a function
>     at b.<anonymous> (debugger-v6.html:48)
>     at f (index.min.js:9)

http://cs1.brightcodes.net/simon/brightcoveplayer/debugger-v6.html

![debuggerv6](https://user-images.githubusercontent.com/400864/27550447-b141e4a4-5a6d-11e7-8bbd-9303744636a1.png)

**Comment by RevinKey** [comment]
I have started working on a new version of the Debugger that uses the latest plugin generator to ensure compatibility with v5 and v6. Currently got passed that error, working now on handling the options in a way that suits both v5 and v6, should have a working branch hopefully within a week

**Comment by RevinKey** [comment]
PR#11

**Comment by danishykj** [comment]
What is the solution to this error? Any ideas

**Comment by marguinbc** [comment]
The PR to address this error was merged and is included in the current release of the debugger.
