### ISSUE TITLE
Clicking "Class" button causes an error

### ISSUE THREAD

**Issue by thase** [marguinbc/brightcove-player-debugger#2]
When I use the plugin, and click the "Class" button in the debugger window, I get the following error.
brightcove-player-debugger.min.js:7 Uncaught ReferenceError: options is not defined(…)

It is reproducible in the following page.
http://cs1.brightcodes.net/thase/solutions/tools/debugger/debugger.html

FYI, I used npm to build the latest source code (as of 11/11/2016), and created "dist" files, and using them in the above page.

**Comment by marguinbc** [comment]
Thanks @thase, this is definitely a bug in that options not defined when the debugger is trying to toggle the classList button.

In the meantime, one workaround I have found is moving the two lines to setup the debugger outside the player.ready() function.

**Comment by RevinKey** [comment]
Latest Version has Fixed this.
